name: Update maplibre-native dependency

on:
  schedule:
    # The first day of every month at 12:00 AM UTC
    - cron: "0 12 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false }
      - name: Install just
        uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
        with:
          tool: just

      - name: Update maplibre-native
        run: just update-maplibre-native

      - name: Get maplibre-native details
        id: maplibre-details
        run: |
          echo "details<<EOF" >> $GITHUB_OUTPUT
          just maplibre-native-info
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update `maplibre-native`"
          title: "chore(deps): update `maplibre-native`"
          body: |
            ## Automated `maplibre-native` dependency update

            This PR updates `package.metadata.mln.release` in `Cargo.toml` to the latest Maplibre Native Core release.

            ${{ steps.maplibre-details.outputs.details }}
          branch: update-maplibre-native-dependency
          delete-branch: true
          labels: dependencies
